import type { Metadata } from 'next';
import './globals.css';
import { Web3ModalWrapper } from './components/web3ModalWrapper';
import ConnectWallet from './components/connectWallet';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <Web3ModalWrapper>
               <ConnectWallet />
               {children}
            </Web3ModalWrapper>
         </body>
      </html>
   );
}
